apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: jenkins-pool
      protocol: layer2
      addresses:
      - 192.168.1.220-192.168.1.220
    - name: awx-pool
      protocol: layer2
      addresses:
      - 192.168.1.221-192.168.1.221
    - name: openvpn-pool
      protocol: layer2
      addresses:
      - 192.168.1.222-192.168.1.222
    - name: dashboard-pool
      protocol: layer2
      addresses:
      - 192.168.1.223-192.168.1.223
    - name: oracle-pool
      protocol: layer2
      addresses:
      - 192.168.1.224-192.168.1.225
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.230-192.168.1.250
    - name: test
      protocol: layer2
      addresses:
      - 192.168.1.251-192.168.1.254
